- name: Update Apache Proxy for New CMS Site
  hosts: "{{lb_ip}}"
  tasks:
  - name: Deploy Virtual Host Template
    template:
      src: cms.temp
      dest: /etc/httpd/conf.d/{{lab_code}}-cms.conf
  - name: Update LABCODE
    replace:
      path: /etc/httpd/conf.d/{{lab_code}}-cms.conf
      regexp: "LABCODE"
      replace: "{{lab_code}}"
  - name: Update CMSLBIP
    replace:
      path: /etc/httpd/conf.d/{{lab_code}}-cms.conf
      regexp: "WWWIP"
      replace: "{{www_ip}}"
  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted
- name: Configure Site Depot CMS WWW Server
  hosts: "{{www_ip}}"
  tasks:
  - name: Deploy Wordpress Config
    template:
      src: wp-config.temp
      dest: /var/www/html/wp-config.php
      owner: apache
      group: apache
      mode: 0644
  - name: Update DBNAME
    replace:
      path: /var/www/html/wp-config.php
      regexp: "DBNAME"
      replace: "{{db_dbname}}"
  - name: Update DBUSER
    replace:
      path: /var/www/html/wp-config.php
      regexp: "DBUSER"
      replace: "{{db_user}}"
  - name: Update DBPASS
    replace:
      path: /var/www/html/wp-config.php
      regexp: "DBPASS"
      replace: "{{db_pass}}"
  - name: Update DBIP
    replace:
      path: /var/www/html/wp-config.php
      regexp: "DBIP"
      replace: "{{db_ip}}"
  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted