- name: Update Apache Proxy for New CMS Site
  hosts: {{lb_ip}}
  tasks:
  - name: Deploy Virtual Host Template
    template:
      src: cms.temp
      dest: /etc/httpd/conf.d/{{lab_code}}-cms.conf
  - name: Update LABCODE
    replace:
      path: /etc/httpd/conf.d/{{lab_code}}-cms.conf
      regexp: "LABCODE"
      replace: "{{lab_code}}"
  - name: Update CMSLBIP
    replace:
      path: /etc/httpd/conf.d/{{lab_code}}-cms.conf
      regexp: "WWWIP"
      replace: "{{www_ip}}"
