- name: Rename LB
  hosts: "{{lb_ip}}"
  tasks:
  - name: Changing Name
    hostname: 
      name: "{{lb_name}}"
  - name: Setting Name Preservation
    lineinfile:
      path: /etc/cloud/cloud.cfg
      regexp: '^# vim'
      insertafter: '^# vim'
      line: 'preserve_hostname: true'
  - name: Restart Server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
- name: Rename WWW
  hosts: "{{www_ip}}"
  tasks:
  - name: Changing Name
    hostname: 
      name: "{{www_name}}"
  - name: Setting Name Preservation
    lineinfile:
      path: /etc/cloud/cloud.cfg
      regexp: '^# vim'
      insertafter: '^# vim'
      line: 'preserve_hostname: true'
  - name: Restart Server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
- name: Rename DB
  hosts: "{{db_ip}}"
  tasks:
  - name: Changing Name
    hostname: 
      name: "{{db_name}}"
  - name: Setting Name Preservation
    lineinfile:
      path: /etc/cloud/cloud.cfg
      regexp: '^# vim'
      insertafter: '^# vim'
      line: 'preserve_hostname: true'
  - name: Restart Server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
- name: Rename Windows Server
  hosts: "{{trap_ip}}"
  gather_facts: false
  tasks:
  - name: Rename Server
    win_shell: Rename-Computer -NewName "{{trap_name}}"
  - name: Reboot
    win_reboot:
