- name: Rename Windows Server
  hosts: all
  gather_facts: false
  tasks:
  - name: Rename Server
    win_shell: wmic computersystem where caption='AnCMSP-Mid-Trap2' rename AnCSC0MidTrap
  - name: Reboot
    win_reboot:

