- name: Rename Linux Server
  hosts: all
  tasks:
    - name: Changing Name
      hostname: 
        name: "{{name}}"
    - name: Setting Name Preservation
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^# vim'
        insertafter: '^# vim'
        line: 'preserve_hostname: true'
    - name: Restart Server
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true