- name: Configure Site Depot CMS WWW Server
  hosts: all
  tasks:
- name: Rename CMS WWW Server
  import_playbook: rename_linux_server.yaml
- name: Trigger ServiceNow Discovery
  import_playbook: servicenow-trigger_discovery.yaml
