- name: ServiceNow Trigger Rediscover (Requires Custom ServiceNow API)
  hosts: all
  tasks:
    - name: Trigger ServiceNow Discovery
      uri:
        url: https://{{instance}}.service-now.com/api/snc/restfulworkflow/AnCQuickDiscover?u_ip={{ip}}
        method: POST
        user: "{{user}}"
        password: "{{pass}}"
        force_basic_auth: yes