- name: Reset Demo in Nagios for WWW Server
  hosts: all
  tasks:
  - name: Remove CMS.CONF file
    command: rm -rf /usr/local/nagios/etc/servers/linux/anc-{{lab_code}}-www.cfg
    register: removefile
  - name: Restart Nagios
    service:
      name: nagios
      state: restarted