- name: Deploy Shared MID Servers
  hosts: all
  gather_facts: false
  tasks:
    - name: Create MID Server Service Directory
      win_shell: copy-item c:\MIDServer\Install-K\agent -destination c:\MIDServer\{{instancename}} -Recurse