- name: Get EC2 Public IP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather EC2 Facts
      ec2_instance_facts:
        region: us-west-2
        filters:
          "tag:Name": "{{name_tag}}"
    - name: Out Put IP
      debug:
        msg: "{{instances.public_ip_address}}"