- name: Repair Nagios Volitile FileSystems after Reboot
  hosts: all
  tasks:
    - name:  Add Spool Dir
      file:
        path: /usr/local/nagios/var/spool/checkresults
        state: directory
        mode: 0775
    - name:  Add RW Dir
      file:
        path: /usr/local/nagios/var/rw
        state: directory
        mode: 0775
    - name: Set Ownership nagios:nagios
      command: chown -R nagios:nagios /usr/local/nagios/var/*
    - name: Restart Nagios
      service:
        name: nagios
        state: restarted