- name: Reset Demo for CMS Loadbalancer
  hosts: all
  tasks:
  - name: Remove CMS.CONF file
    command: rm -rf /etc/httpd/conf.d/{{lab_code}}-cms.conf
    register: removefile
  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted