- name: Site Depot-CMS-TRAP-Initial Config 
  hosts: all
  gather_facts: true
  tasks:
- name: Rename CMS WWW Server
  import_playbook: rename_windows_server.yaml
- name: Run ServiceNow Discovery
  import_playbook: servicenow-trigger_discovery_windows.yaml
