- name: Site Depot-CMS-TRAP-Initial Config 
  hosts: all
  gather_facts: false
  tasks:
  - setup:
    register: ansible_facts
  - debug: item
    with_dict: ansible_facts
- name: Rename CMS WWW Server
  import_playbook: rename_windows_server.yaml
