- name: ServiceNow Trigger Rediscover (Requires Custom ServiceNow API)
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Trigger ServiceNow Discovery
      uri:
        url: https://{{discovery_instance}}.service-now.com/api/snc/restfulworkflow/ITOMCMSDeploy?u_hostip={{ansible_ip_addresses[0]}}&u_hostname={{ansible_hostname}}
        method: POST
        user: websrvc
        password: Aw3s0m34321
        force_basic_auth: yes