- name: Update Zabbix Config and Restart Service
  hosts: all
  tasks:
  - name: Update Zabbix Config
    template:
      src: files/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
  - name: Restart Zabbix
    service:
      name: zabbix-agent
      state: restarted